version: '2'
services:
    todosampleapp-app:
        image: todosampleapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://todosampleapp-mysql:3306/todosampleapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8010:8010
    todosampleapp-mysql:
        extends:
            file: mysql.yml
            service: todosampleapp-mysql
